apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mb-intake
resources:
  - ../../base/mb-intake
  - mb-admin-mongo-env.yaml
  - cloudflare.yaml
  - ingress.yaml
  - cloudflare-secret.yaml
