apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jXJWdcngLhJaaqIpZUSHvYvYzCG8usZJ9VePvg6S/YH7i148FlcCobMqNhukMQq19oMlk7K8wzcQRqehL5/CTWS/ax9QFUfnj8vawtQ3b758g/CUzEp5LOExNLfRNNiHArNDj3nA+5u6A1x4fIJU12jZ1iXIzmDYs0j25h/vsfZ2M6QO13dzadJX3BHtjapRCK6BTuSReRsV5wjjltn38Ltbe0wYcI4B/tFIf1wlP60zfU3JzadsVBM4ijQ5JKtEBM/9lAUFqxGMO+wS4VZ7yNRLK+ojnpXr,iv:FiykUehr1crqm2eqd7I3TYCzh6kIn5deIxs5IHJj7M8=,tag:dxWf1Hh/SaFFN8wxagDvSQ==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1077lsst7gx63xavswcv2ru8wu4rj6cz5ak6y6nnkaq9yp759z4ms54w0kp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3RnpjdzRuTzJpb09HQkE5
            bWJvWXRqWm9seXZaMHVNOTVMYk1idUlkSTJjCk9mdWF3UHo0Qk5WYUowSFhNK0k2
            RGNSVGl4dktLTjN6T1RFWnhtVElHWWcKLS0tIDIrdzNTWTFaUVZuY1RiSXRUL2gx
            WEw2VklEZXlUdjk4dnNDRkxTV1luRW8KU7decKPfIXMjGg9/bvNkASecDSidlol6
            FSAKDJXXtZ/Zc/5C11xsnQQdzq2pCLgDDNI+d8TgoaNC4SA/fpk7Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T05:16:01Z"
    mac: ENC[AES256_GCM,data:zxGrzAxZZ4i3P5Ajw+XkH4P68CwXmUUVaDfaVs3J3rOLBokGHauPZ3IOokuFICpn0nBfK/Am3Jx8OXtvlNvhJu4aqmki2SkKliOy0YFFvdvPRUpdAxny1nE+DGj6SV/OzaQ78563kSVTmcRAY+RJTkSfJXe5X4jthmHmg36bG4Y=,iv:zPFrY5ApZK4ibls6JAXWGeTcZzd3mHAK80MSocEIfZQ=,tag:rnn3PbBQmrsmYtRQ8iRXzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
