apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding
resources:
  - ../../base/linkding
  - cloudflare.yaml
  - ingress.yaml
  - cloudflare-secret.yaml
  - login-secret.yaml
