apiVersion: v1
data:
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:kTo8xQ==,iv:KUbQLuQSCWu62GkD5htWxs0tw+RwGSqFqnDR8V2ti/g=,tag:SZ6nxa0x35Cs9Y/SOafCAQ==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:ChVkdNPi1+ITUPIA49qXbjz/hUAtuCxyepJX1w==,iv:c298CQbKXZjH/vtQTgB+aZG5O2cQU7HVGCZ/dex/bus=,tag:GkdhudZHLz6dwHrgkTxWdQ==,type:str]
kind: Secret
metadata:
  name: linkding-container-env
  namespace: linkding
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1077lsst7gx63xavswcv2ru8wu4rj6cz5ak6y6nnkaq9yp759z4ms54w0kp
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dm54UXM1ZU9uVjlpbk94
        dmYwaERFVU94b1JOZjdXNUsvWDNwWUFOVml3Cjh4aDhyMHlDYlFnVXFxaDVlbStR
        Z2JOajhLbEJrSFo2Rm9LNy9oZmVLeHcKLS0tIGdCQUQ0M2U2OGtBWGljckkxU1ZT
        RHhaNC9NU0p4SmV3RVBPZHJ5ZlpkZXcKYfYJpBr+qbnHVUWCORYbpzwbhFi5CFrY
        4glLdtjXyt/det0m8wc3CVb9rPHFBFQM+ARZvI0MxQU3o5qtoWNhSQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-12T05:19:44Z"
  mac: ENC[AES256_GCM,data:TkRgXr9aoFfaax9+bZfGS6T11yoeGaCFlU80l2HzQFgfpHD1CCsdVozWzP6EEv8RKnS/DMngcnH5tijiJb+5w3jf2NsUHOmtxGb6j97wRmBrun7wIJBvoCGx4u+90PMk/+zcvOkEL1RDkKtO8+5+SgCEhUAxkoka+hIrDpL6sD0=,iv:UrizgyAM+1Jv06iHW0TxgVxHy0hcYixDSj70M/24dDA=,tag:JcwNt+xOb0MqjBp8CftdFg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
