apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k3s.io/hostname
              operator: "In"
              values: ["pi5-server"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: linkding-data-pv
  resources:
    requests:
      storage: 1Gi
